# Math Problem Set 6 

## Problem 9.6

In [1]:
import numpy as np
import sympy as sy
from sympy import *
import pandas as pd
from matplotlib import pyplot as plt
from scipy import linalg 
max_line_width=np.inf

In [2]:
def gradient_descent(tol, x_0,b,Q):
    iters = 0
    error = 10
    maxiter = 100
    while error > tol and iters < maxiter:
        Dft =  Q@x_0-b
        α_num = Dft.T@Dft
        α_den = Dft.T@Q@Dft
        α = α_num/α_den
        x_1 = x_0 - α*Dft
        error =  linalg.norm(x_1-x_0,2)
        iters = iters +1
        x_0 = x_1
        f_val = 0.5*(x_0.T@Q@x_0) - b.T@x_0
    return x_0,f_val


        
A = np.random.random(9).reshape(3,3)
Q = A@A.T
b = np.array([10, 10,10])
x_0 = np.array([3, 9,9])

gradient_descent(1e-4,x_0,b,Q)

(array([  5.59046864, -11.41719028,  38.28498286]), -162.29194858820895)

In [3]:
def jacobian(func,x_vec,Rerrf):
    h = Rerrf**0.5
    n= len(x_vec)
    basis =  np.eye(n)
    jac = np.zeros((n))
    for j in range(n):
        jac[j] = (1/h)*(func(x_vec+ h*basis[:,j])-func(x_vec))
    return jac

In [4]:
F = np.array([[1., 2.], [3., 4.]])
f = lambda x: (F @ x).T @ (F @ x)
x = np.array([1.,1.])
f(x)
jacobian(f, x, .01)

rosenbrock = lambda x: 100*(x[1]-x[0]**2)**2 + (1-x[0])**2

jacobian(rosenbrock, x, .01)


array([44.2, 10. ])

In [17]:
def steepest_descent(f, x0, eps):
    maxiter = 3*1e5
    iters = 1
    err =  1+eps
    while err > eps and iters < maxiter:
        Dfx = jacobian(f, x0, eps)
        f_alpha_prime = lambda x: jacobian(f, x0 - x * Dfx.T, eps) @ (-1 * Dfx.T)
        opt_alpha = secant(.9, 1.1, eps, f_alpha_prime)
        x1 = x0 - opt_alpha * Dfx
        err = np.linalg.norm(Dfx,2)
        x0 = x1
        iters += 1
    return x0
x0 = np.array([-1.,1.5])
steepest_descent(rosenbrock,x0,1e-5)

array([0.5899992 , 0.34651782])