In [1]:
#problem 1
import numpy as np
A = np.array([[3, -1, 4],[1, 5, -9]])
print(A)
B = np.array([[2, 6, -5, 3],[5, -8, 9, 7],[9, -3, -2,-3]])
np.dot(A, B)

[[ 3 -1  4]
 [ 1  5 -9]]


array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [2]:
# problem 2
def prob2():
    
    A = np.array([[3, 1, 4],[1, 5, 9],[-5, 3, 1]])
    return -(A@A@A) + 9*(A@A) - 15 * A


In [3]:
prob2()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [4]:
#prob 3 
def prob3():
    A = np.ones((7, 7), dtype=np.int)
    A = np.triu(A)
    B = 5 * np.ones((7,7), dtype=np.int)
    B = np.triu(B, k=1)
    C = -1 * np.ones((7,7), dtype=np.int)
    C= np.tril(C)
    D= B + C
    prob3 = A@D@A
    prob3 = prob3.astype(np.int64)
    return prob3

    


In [5]:
prob3()


array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]], dtype=int64)

In [6]:
x = np.arange(11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
x[3]

3

In [8]:
#prob4
def prob4(a):
    b = np.copy(a)
    mask = b < 0
    b[mask] = 0
    return b


In [9]:
a = [2, -5, 0, 2]
prob4(a)

array([2, 0, 0, 2])

In [10]:
#prob5
def prob5():
    A = np.arange(6).reshape(2,3)
    B = np.tril(3 * np.ones((3,3)))
    C = -2 * np.eye(3)
    D = np.hstack((np.zeros((3, 3)), A.T, np.eye(3)))
    E = np.hstack((A, np.zeros((2,2)), np.zeros((2, 3))))
    F = np.hstack((B, np.zeros((3,2)), C))
    final = np.vstack((D, E, F))
    return final


In [11]:
prob5()

array([[ 0.,  0.,  0.,  0.,  3.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  4.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  2.,  5.,  0.,  0.,  1.],
       [ 0.,  1.,  2.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  4.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2., -0., -0.],
       [ 3.,  3.,  0.,  0.,  0., -0., -2., -0.],
       [ 3.,  3.,  3.,  0.,  0., -0., -0., -2.]])

In [12]:
A = np.arange(6).reshape((2,3))
print(A) 
np.sum(A, axis=0)
np.sum(A, axis=1)


[[0 1 2]
 [3 4 5]]


array([ 3, 12])

In [13]:
np.array([min(A[:,i]) for i in range(3)])

array([0, 1, 2])

In [14]:
A = np.arange(12).reshape((4,3))
A_new =(np.array(A.sum(axis = 1)))
X = A_new.reshape((4,1))
A_z = A/X
A_z


array([[0.        , 0.33333333, 0.66666667],
       [0.25      , 0.33333333, 0.41666667],
       [0.28571429, 0.33333333, 0.38095238],
       [0.3       , 0.33333333, 0.36666667]])

In [15]:
# problem 7
import numpy as np
def grid_max():
    
    grid = np.load("grid.npy")

    horizontal = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    vertical = np.max(grid.T[:,:-3] * grid.T[:,1:-2] * grid.T[:,2:-1] * grid.T[:,3:])
    diagmain = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
    diag_rev = np.max(grid[3:,:-3] * grid[2:-1,1:-2] * grid[1:-2,2:-1] * grid[:-3,3:])
    
    return max(horizontal,vertical,diagmain,diag_rev)

grid_max()

70600674