In [102]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import scipy as spy
from scipy import linalg as la


In [105]:
A = np.random.random((6,4))
def GS(A):
    m,n=np.shape(A)
    Q= np.copy(A)
    Q=Q.astype(float)
    R = np.zeros([n,n])
    for i in range(0, n):
        R[i, i]=scipy.linalg.norm(Q[:,i])
        Q[:,i] =Q[:,i]/R[i,i]
        for j in range(i+1, n):
            R[i,j] = np.array(np.matrix(Q[:,j]) @ np.matrix(Q[:,i]).T)
            Q[:,j] = Q[:,j]- R[i,j]*Q[:,i]
    return Q,R
        
x,y = GS(A);
z,mm = la.qr(A, mode= "economic");
print(y-mm)


[[2.7625633  1.28288293 3.39362066 2.68416681]
 [0.         1.86716622 0.96169084 0.57656778]
 [0.         0.         0.91651565 0.18397667]
 [0.         0.         0.         0.99292756]]


In [98]:
#SInce the determinant of A is just the product of elements of the diagonal in the matrix 
#or the r[i,i] , we can get it done.
def Det(A):
    Q, R= la.qr(A, mode="economic")
    det_A = abs(R.diagonal().prod())
    return det_A
A =([1,1],
  [1,1])
A = np.mat(A)
print(Det(A))
print(la.det(A))
print(Det(A) - la.det(A)) #to check though trivial

6.70940890281045e-17
0.0
6.70940890281045e-17


In [ ]:

#Question 3                       
def back_substitution(A, b):
    n = b.size
    x = np.zeros((n,1))
    x[n-1] = b[n-1] / A[n-1, n-1]
    for i in range(n-2, -1, -1):
        solv = b[i]
        for j in range(i+1, n):
            solv = solv - A[i,j] * x[j]
        x[i] = solv / A[i,i]
    return x


def solve_linear(A,b):
    Q,R = g2_schmidt(A)
    y = Q.T@b
    return back_substitution(R,y)

A=np.array( [2,3,4,9,-4,30,1,1,-1])
A =A.reshape((3,3))
A = np.matrix(A)
b =np.array([38,161,2])
b = np.matrix(b.reshape(3,1))


wer = solve_linear(A,b)
print(wer.tolist())

    

In [99]:
# solution 4
def HH(A):
    m, n = shape.A
    R = np.copy(A)
    Q = np.matrix(np.identity(m))
    for k in range (0,n):
        u = np.copy(R[k:, k])
        sign = lambda x: 1 if  x >=0 else -1
        u[0] = u[0] + sign(u[0])*np.linalg.norm(u)
        u = u/np.linalg.norm(u)
        R[k:,k:] = R[k:,k:]- 2*u @ (np.trans(u) @ R[k:,k:])
        Q[k:,:] = Q[k:,:]- 2* u @ (np.trans(u) @ Q[k:,:])
    return np.trans(Q), R
        
A = np.random.random((5,3))
Q, R = np.linalg.qr(A)
print(A.shape, Q.shape, R.shape)
np.allclose(Q @ R, A)
        
  #Could not understand why to use outer product and why it is different from above      

(5, 3) (5, 3) (3, 3)


True

In [103]:

#solution 4
def Hessenberg(A):
    m,n = A.shape
    H = np.copy(A)
    Q = np.eye(m)
    for k in range(n-2):
        u = np.copy(H[k+1:,k])
        sign = lambda x: 1 if  x >=0 else -1
        u[0]= u[0] + sign(u[0])*spy.linalg.norm(u)
        u = u/spy.linalg.norm(u)
        H[k+1:,k:] = H[k+1:,k:] - 2*np.outer(u, u.T@H[k+1:,k:])
        H[:,k+1:] = H[:,k+1:] - 2*np.outer(H[:,k+1:]@u,u.T)
        Q[k+1:,:] = Q[k+1:,:] - 2*np.outer(u, u.T@Q[k+1:,])
    return H,Q.T

A = np.random.random((10, 10))
H,Q = spy.linalg.hessenberg(A, calc_q =True)

np.allclose(np.triu(H,-1),H)
HH,QQ = Hessenberg(A)
np.allclose(QQ@HH@QQ.T,A)

True